spring:
  application:
    name: aml-warehouse-backend
  profiles:
    active: h2

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb://aml_user:aml_pass@localhost:27017/aml_dw?authSource=admin
      auto-index-creation: true

  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/schema.sql
      data-locations: classpath:db/migration/data.sql
      continue-on-error: false

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always

aml:
  jwt:
    secret: ZmFrZS1zZWNyZXQta2V5LWZvci1hbWwtZGF0YS13YXJlaG91c2UtcHJvdG90eXBlLW9ubHk=
    access-token-validity-ms: 28800000   # 8 hours
    refresh-token-validity-ms: 604800000 # 7 days
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000
  audit:
    enabled: true
  pii:
    masking-roles: AML_ANALYST,RISK_ANALYST,AUDITOR

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.bank.amlwarehouse: DEBUG
    org.hibernate.SQL: WARN

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:amldw;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/aml_dw
    driver-class-name: org.postgresql.Driver
    username: aml_user
    password: aml_pass
  sql:
    init:
      mode: never   # schema is loaded by docker-entrypoint
