-- ============================================================================
--  AML Data Warehouse — DDL
--  Compatible with PostgreSQL 15 and H2 in PostgreSQL mode.
-- ============================================================================

/* -------------------------- SECURITY -------------------------- */
CREATE TABLE IF NOT EXISTS sec_role (
    role_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code   VARCHAR(64)  NOT NULL UNIQUE,
    role_name   VARCHAR(128) NOT NULL,
    description VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS sec_user (
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(64)  NOT NULL UNIQUE,
    full_name      VARCHAR(128) NOT NULL,
    email          VARCHAR(128),
    password_hash  VARCHAR(255) NOT NULL,
    branch_code    VARCHAR(16),
    department     VARCHAR(64),
    active         BOOLEAN DEFAULT TRUE,
    last_login_at  TIMESTAMP WITH TIME ZONE,
    created_at     TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS sec_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_sur_user FOREIGN KEY (user_id) REFERENCES sec_user(user_id),
    CONSTRAINT fk_sur_role FOREIGN KEY (role_id) REFERENCES sec_role(role_id)
);

CREATE TABLE IF NOT EXISTS sec_permission (
    permission_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(64) NOT NULL UNIQUE,
    description     VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS sec_role_permission (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id)
);

/* -------------------------- MASTER ---------------------------- */
CREATE TABLE IF NOT EXISTS mst_branch (
    branch_code  VARCHAR(16) PRIMARY KEY,
    branch_name  VARCHAR(128),
    city         VARCHAR(64),
    state        VARCHAR(64),
    country_code VARCHAR(8),
    ifsc_code    VARCHAR(16)
);

CREATE TABLE IF NOT EXISTS mst_customer (
    customer_id          VARCHAR(32) PRIMARY KEY,
    customer_name        VARCHAR(128) NOT NULL,
    customer_type        VARCHAR(32),
    date_of_birth        DATE,
    gender               VARCHAR(16),
    occupation           VARCHAR(64),
    industry             VARCHAR(64),
    nationality          VARCHAR(64),
    country_code         VARCHAR(8),
    branch_code          VARCHAR(16),
    kyc_status           VARCHAR(32),
    risk_rating          VARCHAR(16),
    pep_flag             BOOLEAN,
    sanction_flag        BOOLEAN,
    adverse_media_flag   BOOLEAN,
    pan_number           VARCHAR(16),
    aadhaar_number       VARCHAR(16),
    mobile               VARCHAR(32),
    email                VARCHAR(128),
    address              VARCHAR(512),
    onboarding_date      DATE,
    status               VARCHAR(16),
    updated_at           TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_cust_risk ON mst_customer(risk_rating);
CREATE INDEX IF NOT EXISTS idx_cust_branch ON mst_customer(branch_code);

CREATE TABLE IF NOT EXISTS mst_account (
    account_number       VARCHAR(32) PRIMARY KEY,
    customer_id          VARCHAR(32) NOT NULL,
    product_code         VARCHAR(16),
    product_name         VARCHAR(64),
    branch_code          VARCHAR(16),
    currency             VARCHAR(8),
    open_date            DATE,
    close_date           DATE,
    status               VARCHAR(16),
    current_balance      NUMERIC(18,2),
    available_balance    NUMERIC(18,2),
    last_transaction_date DATE,
    dormant_flag         BOOLEAN,
    dormancy_period_days INT,
    updated_at           TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_acct_cust FOREIGN KEY (customer_id) REFERENCES mst_customer(customer_id)
);
CREATE INDEX IF NOT EXISTS idx_acct_customer ON mst_account(customer_id);

/* -------------------------- FACT ------------------------------ */
CREATE TABLE IF NOT EXISTS fact_transaction (
    transaction_id        VARCHAR(32) PRIMARY KEY,
    account_number        VARCHAR(32) NOT NULL,
    customer_id           VARCHAR(32),
    transaction_date      TIMESTAMP WITH TIME ZONE NOT NULL,
    value_date            TIMESTAMP WITH TIME ZONE,
    transaction_type      VARCHAR(16),
    transaction_mode      VARCHAR(32),
    channel               VARCHAR(16),
    amount                NUMERIC(18,2) NOT NULL,
    currency              VARCHAR(8),
    counterparty_name     VARCHAR(256),
    counterparty_account  VARCHAR(64),
    counterparty_bank     VARCHAR(128),
    counterparty_country  VARCHAR(8),
    is_cash               BOOLEAN,
    is_cross_border       BOOLEAN,
    is_high_value         BOOLEAN,
    branch_code           VARCHAR(16),
    narration             VARCHAR(512),
    status                VARCHAR(16)
);
CREATE INDEX IF NOT EXISTS idx_txn_account  ON fact_transaction(account_number);
CREATE INDEX IF NOT EXISTS idx_txn_customer ON fact_transaction(customer_id);
CREATE INDEX IF NOT EXISTS idx_txn_date     ON fact_transaction(transaction_date);

CREATE TABLE IF NOT EXISTS fact_alert (
    alert_id               VARCHAR(32) PRIMARY KEY,
    alert_type             VARCHAR(16),
    rule_code              VARCHAR(64),
    rule_name              VARCHAR(256),
    customer_id            VARCHAR(32),
    account_number         VARCHAR(32),
    transaction_id         VARCHAR(32),
    branch_code            VARCHAR(16),
    risk_score             INT,
    priority               VARCHAR(16),
    status                 VARCHAR(32),
    assigned_to            VARCHAR(64),
    threshold_value        NUMERIC(18,2),
    actual_value           NUMERIC(18,2),
    no_match_reason        VARCHAR(256),
    false_positive_reason  VARCHAR(256),
    closure_comments       VARCHAR(1024),
    investigator_comments  VARCHAR(1024),
    checker_user           VARCHAR(64),
    alert_date             TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at              TIMESTAMP WITH TIME ZONE,
    aging_days             INT
);
CREATE INDEX IF NOT EXISTS idx_alert_customer ON fact_alert(customer_id);
CREATE INDEX IF NOT EXISTS idx_alert_status   ON fact_alert(status);
CREATE INDEX IF NOT EXISTS idx_alert_type     ON fact_alert(alert_type);

CREATE TABLE IF NOT EXISTS fact_str (
    str_id                 VARCHAR(32) PRIMARY KEY,
    customer_id            VARCHAR(32),
    account_number         VARCHAR(32),
    alert_id               VARCHAR(32),
    branch_code            VARCHAR(16),
    suspicious_indicators  VARCHAR(2048),
    narrative              TEXT,
    total_amount           NUMERIC(18,2),
    transaction_count      INT,
    status                 VARCHAR(32),
    maker_user             VARCHAR(64),
    checker_user           VARCHAR(64),
    filed_with             VARCHAR(64),
    fir_reference          VARCHAR(64),
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    submitted_at           TIMESTAMP WITH TIME ZONE,
    approved_at            TIMESTAMP WITH TIME ZONE,
    filed_at               TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS fact_ctr (
    ctr_id            VARCHAR(32) PRIMARY KEY,
    customer_id       VARCHAR(32),
    account_number    VARCHAR(32),
    branch_code       VARCHAR(16),
    report_date       DATE,
    transaction_count INT,
    total_cash_amount NUMERIC(18,2),
    threshold_amount  NUMERIC(18,2),
    currency          VARCHAR(8),
    status            VARCHAR(32),
    approver_user     VARCHAR(64),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    approved_at       TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS fact_dormant_account (
    account_number              VARCHAR(32) PRIMARY KEY,
    customer_id                 VARCHAR(32),
    branch_code                 VARCHAR(16),
    last_transaction_date       DATE,
    dormancy_period_days        INT,
    dormancy_status             VARCHAR(32),
    reactivation_date           DATE,
    suspicious_reactivation_flag BOOLEAN,
    alert_generated             BOOLEAN
);

CREATE TABLE IF NOT EXISTS fact_loan_application (
    application_id   VARCHAR(32) PRIMARY KEY,
    customer_id      VARCHAR(32),
    loan_type        VARCHAR(8),
    product_name     VARCHAR(128),
    amount           NUMERIC(18,2),
    tenure_months    INT,
    interest_rate    NUMERIC(6,3),
    credit_score     INT,
    aml_risk         VARCHAR(16),
    linked_alerts    INT,
    status           VARCHAR(32),
    branch_code      VARCHAR(16),
    applied_on       DATE,
    decisioned_on    DATE
);
CREATE INDEX IF NOT EXISTS idx_loan_type     ON fact_loan_application(loan_type);
CREATE INDEX IF NOT EXISTS idx_loan_customer ON fact_loan_application(customer_id);

/* -------------------------- DW & GOVERNANCE ------------------- */
CREATE TABLE IF NOT EXISTS dw_data_catalogue (
    catalogue_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_system       VARCHAR(64),
    source_table        VARCHAR(128),
    source_field        VARCHAR(128),
    table_name          VARCHAR(128),
    column_name         VARCHAR(128),
    data_type           VARCHAR(64),
    business_definition VARCHAR(1024),
    data_owner          VARCHAR(128),
    data_quality_score  INT,
    pii_flag            BOOLEAN,
    aml_relevance       VARCHAR(16),
    domain              VARCHAR(64)
);
CREATE INDEX IF NOT EXISTS idx_cat_table    ON dw_data_catalogue(table_name);
CREATE INDEX IF NOT EXISTS idx_cat_relevance ON dw_data_catalogue(aml_relevance);

CREATE TABLE IF NOT EXISTS dw_etl_job (
    job_id            VARCHAR(32) PRIMARY KEY,
    job_name          VARCHAR(128),
    source_system     VARCHAR(64),
    target_table      VARCHAR(128),
    load_type         VARCHAR(16),
    status            VARCHAR(16),
    start_time        TIMESTAMP WITH TIME ZONE,
    end_time          TIMESTAMP WITH TIME ZONE,
    records_extracted BIGINT,
    records_loaded    BIGINT,
    records_rejected  BIGINT,
    error_message     VARCHAR(2048)
);

CREATE TABLE IF NOT EXISTS dw_data_quality_issue (
    issue_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code   VARCHAR(64),
    rule_name   VARCHAR(256),
    table_name  VARCHAR(128),
    column_name VARCHAR(128),
    issue_type  VARCHAR(64),
    severity    VARCHAR(16),
    record_count BIGINT,
    status      VARCHAR(16),
    assigned_to VARCHAR(64),
    detected_at TIMESTAMP WITH TIME ZONE,
    resolved_at TIMESTAMP WITH TIME ZONE
);

/* -------------------------- AUDIT ----------------------------- */
CREATE TABLE IF NOT EXISTS audit_user_activity (
    audit_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64),
    module_name   VARCHAR(64),
    action        VARCHAR(64),
    status        VARCHAR(16),
    error_message VARCHAR(1024),
    duration_ms   BIGINT,
    ip_address    VARCHAR(64),
    activity_time TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_audit_user   ON audit_user_activity(username);
CREATE INDEX IF NOT EXISTS idx_audit_module ON audit_user_activity(module_name);
CREATE INDEX IF NOT EXISTS idx_audit_time   ON audit_user_activity(activity_time);

/* The remaining warehouse tables are documented in docs/extra-ddl.sql for the
   full enterprise schema. For the prototype we keep DDL focused on what the
   APIs actively read / write to keep boot-time tiny.                         */
